### ISSUE TITLE
Problem loading grammar

### ISSUE THREAD

**Issue by AzierAriel** [thep0y/python-black#10]
Hi!

First of all, thanks for the project!

After today's update i got the following error when I try to run black on ST 4126, Ubuntu 20.04

```Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python38/sublime_plugin.py", line 1518, in run_
    return self.run(edit)
  File "/home/***/.config/sublime-text/Installed Packages/python-black.sublime-package/commands.py", line 50, in run
  File "/home/***/.config/sublime-text/Packages/python-black/python_black/utils.py", line 200, in black_format
  File "/home/***/.config/sublime-text/Packages/python-black/python_black/utils.py", line 177, in format_by_import_black_package
  File "/home/***/.config/sublime-text/Installed Packages/python-black.sublime-package/python_black/black.py", line 16, in <module>
  File "/home/***/.config/sublime-text/Installed Packages/python-black.sublime-package/python_black/lib/black/__init__.py", line 7, in <module>
  File "/home/***/.config/sublime-text/Installed Packages/python-black.sublime-package/python_black/lib/black/nodes.py", line 36, in <module>
  File "/home/***/.config/sublime-text/Installed Packages/python-black.sublime-package/python_black/lib/blib2to3/pygram.py", line 180, in initialize
  File "/home/***/.config/sublime-text/Installed Packages/python-black.sublime-package/python_black/lib/blib2to3/pgen2/driver.py", line 309, in load_packaged_grammar
  File "/home/***/.config/sublime-text/Installed Packages/python-black.sublime-package/python_black/lib/blib2to3/pgen2/grammar.py", line 129, in loads
TypeError: a bytes-like object is required, not 'NoneType'
```

**Comment by thep0y** [comment]
Sorry, I will fix this bug as soon as possible.

If you know how to fix this bug, you are welcome to submit a pr.

From My iPhone
