### ISSUE TITLE
ST is unable to find black module

### ISSUE THREAD

**Issue by joshuaimmanuel** [thep0y/python-black#8]
After installing the `python-black` plugin in ST 4121 running on Ubuntu 20.04.3, I get the following error message while trying to format the python code.

```
Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python38/sublime_plugin.py", line 1518, in run_
    return self.run(edit)
  File "/home/joshua/.config/sublime-text/Installed Packages/python-black.sublime-package/commands.py", line 44, in run
  File "/home/joshua/.config/sublime-text/Installed Packages/python-black.sublime-package/python_black/utils.py", line 200, in black_format
  File "/home/joshua/.config/sublime-text/Installed Packages/python-black.sublime-package/python_black/utils.py", line 177, in format_by_import_black_package
  File "/home/joshua/.config/sublime-text/Packages/python-black/python_black/black.py", line 8, in <module>
    from black import format_str  # type: ignore
ModuleNotFoundError: No module named 'black'
```

**Comment by joshuaimmanuel** [comment]
It was expecting a `.config/sublime-text/Packages/python-black/md5` file and it was failing at the `open(md5_file, "r")` operation complaining that the file does not exist.

```python
        installed_pkg_md5 = md5(installed_pkg_path)
        md5_file = os.path.join(python_black_path, "md5")

        if not installed_pkg_md5 or not md5_file:
            raise Exception("Invalid md5")

        with open(md5_file, "r") as f:
            saved_md5 = f.read()
```

When I manually created the `.config/sublime-text/Packages/python-black/md5` file  with contents matching `installed_pkg_md5`, the issue got resolved.

**Comment by thep0y** [comment]
@ofen There is an issue after merge your pr, can you check it?
